HEISDF.DataPath.Base: C:/HEIS/
HEISDF.DataPath.Compressed: DataCompressed/
HEISDF.DataPath.Access: DataAccess/
HEISDF.DataPath.RawParquet: DataRawParquet/
HEISDF.DataPath.RawRDS: DataRawRDS/
HEISDF.DataPath.ProcessedParquet: DataProcessedParquet/
HEISDF.DataPath.ResultsParquet: DataResultsParquet/
HEISDF.Path.Weights: InputData/SamplingWeights/
HEISDF.Path.CountyCodes: InputData/CountyCodes8791/
HEISDF.DataPath.D80LinkDest: C:/HEIS/DataAccess/D80Link.accdb
HEISDF.Path.D80LinkSource: Tools/D80Link.accdb
HEISDF.Path.MetaDataFiles: MetaData
HEISDF.Path.InflationDataFile: InputData/Inflation.csv
StartYear: 1384.0
EndYear: 1400.0
OutFoodKCXShare: 0.3
OutFoodKCXShare12: 0.4
OutFoodKCXShare3456: 0.2
OutFoodKCXShare78910: 0.1
SectorsNumbers:
- 1
- 2
- 3
- 4
- 5
SectorsNames:
- Public
- Cooperative
- Private
- BussP
- Agri
ConsumptionCols:
- OriginalFoodExpenditure
- FoodOtherExpenditure
- Cigar_Exp
- Cloth_Exp
- Amusement_Exp
- Communication_Exp
- House_Exp
- Energy_Exp
- Furniture_Exp
- Hotel_Exp
- Restaurant_Exp
- Hygiene_Exp
- Transportation_Exp
- Other_Exp
- Add_to_NonDurable
- OwnedDurableItemsDepreciation
ExpenditureCols:
- OriginalFoodExpenditure
- FoodOtherExpenditure
- Cigar_Exp
- Cloth_Exp
- Amusement_Exp
- Communication_Exp
- House_Exp
- Energy_Exp
- Furniture_Exp
- Hotel_Exp
- Restaurant_Exp
- Hygiene_Exp
- Transportation_Exp
- Other_Exp
- Add_to_NonDurable
- Medical_Exp
- Durable_Dep
- Durable_NoDep
- Durable_Emergency

