BaseBundleYear: 1395.0
KCaloryNeed_Adult: 2100.0
KCaloryNeed_Adult_WorldBank: 2100.0
KCaloryNeed_Adult_NutritionInstitute: 2400.0
KCaloryNeed_Child: 1800.0
KCaloryNeed_B1: 850.0
KCaloryNeed_G1: 780.0
KCaloryNeed_B2: 1250.0
KCaloryNeed_G2: 1190.0
KCaloryNeed_B3: 1430.0
KCaloryNeed_G3: 1330.0
KCaloryNeed_B4: 1560.0
KCaloryNeed_G4: 1440.0
KCaloryNeed_B5: 1690.0
KCaloryNeed_G5: 1540.0
KCaloryNeed_B6: 1980.0
KCaloryNeed_G6: 1730.0
KCaloryNeed_B7: 2370.0
KCaloryNeed_G7: 2040.0
KCaloryNeed_B8: 2700.0
KCaloryNeed_G8: 2120.0
KCaloryNeed_B9: 2460.0
KCaloryNeed_G9: 1990.0
KCaloryNeed_B10: 2010.0
KCaloryNeed_G10: 1780.0
KCaloryNeed_NutInst_B1: 705.0
KCaloryNeed_NutInst_G1: 643.0
KCaloryNeed_NutInst_B2: 948.0
KCaloryNeed_NutInst_G2: 865.0
KCaloryNeed_NutInst_B3: 1120.0
KCaloryNeed_NutInst_G3: 1047.0
KCaloryNeed_NutInst_B4: 1360.0
KCaloryNeed_NutInst_G4: 1242.0
KCaloryNeed_NutInst_B5: 1927.0
KCaloryNeed_NutInst_G5: 1782.0
KCaloryNeed_NutInst_B6: 3036.0
KCaloryNeed_NutInst_G6: 2434.0
KCaloryNeed_NutInst_B7: 3029.0
KCaloryNeed_NutInst_G7: 2300.0
KCaloryNeed_NutInst_B8: 2900.0
KCaloryNeed_NutInst_G8: 2200.0
KCaloryNeed_NutInst_B9: 2350.0
KCaloryNeed_NutInst_G9: 2000.0
KCaloryNeed_lactating: 500.0
InitialPoorPercentileMax: 35.0
AgeBreaks:
- -1.0
- 0.0
- 4.0
- 9.0
- 14.0
- 19.0
- 24.0
- 29.0
- 34.0
- 39.0
- 44.0
- 49.0
- 54.0
- 59.0
- 64.0
- 69.0
- 74.0
- 79.0
- 84.0
- 89.0
- 94.0
- 100.0

